# -*- coding: utf-8 -*-
"""Find Directory FileName with Search Pattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WCuc5Yxc9m88OSr_r3hwtbkpFs0cojz7

# Find Directory FileName with Search Pattern
"""

import os

def find_matching_files(directory_path, search_patterns, limit=100):
  """
  Find files in directory that contain any substring from search_patterns in their filenames.

  Args:
  - directory_path (str): The path to the directory to search.
  - search_patterns (list): A list of strings to search for in the filenames.
  - limit (int): Maximum number of files to retrieve. Defaults to 100.

  Returns:
  - List of strings: Paths of the files that match the criteria.
  """
  pdf_files = []
  count = 0

  for root, dirs, files in os.walk(directory_path):
      for file in files:
          filename = file.split('.')[0]
          if file.lower().endswith(".pdf"):
            if any(item.lower() in filename.lower() for item in search_patterns):
                pdf_files.append(os.path.join(root, file))
                count += 1
                if count == limit:
                    return pdf_files

  return pdf_files